
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quizzis",
  description: "Generated by shinchan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">      
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <head>
        <link rel="icon" type='image/png' href="./icon.png" />
      </head>

        {children}
      </body>
    </html>
  );
}
